hng/tech-coops

README.md

Discovered via @davidbgk · https://mastodon.social/users/dav/updates/2408263.

Add _dtc innovation_ coop

---

README.md

Agaric is worker-owned cooperative building websites and providing online technology consulting since 2006.
Thanks for maintaining this list!

Add Agaric to coops list

---

README.md

Our cooperative is seven years old. We are part of the solidarity economy movement, and we develop systems for movements on agriarian reform, agroecology, popular education, and other. We are seven member working in a true autogestionary model. The mission of our coop is to strengthen the struggles of social movements in the popular field through the development of open source IT and participatory methodologies for their use and appropriation.
Congratulations for this great resource,  and please fell free to share any doubts.

Include EITA

---

README.md

We are a co-op based in France. We just found out this list and would like to propose our inclusion.
As a side note: we are also developing a network of tech coop in France, but the website is not done yet and we are still in the early beginnings.

Added Digicoop in the list of co-ops

---

README.md

Cooperative organization in Barcelona, Catalonia created to help promote
social change, especially in the sector of food consumption (See
http://www.katuma.org/) (Open Food Network) but also contributes substantially to the
[Timeoverflow](https://twitter.com/timeoverflow) time bank org and
works closely with [a large range of non-profits/social change organizations](http://coopdevs.org/) in Catalonia.
You can contact @enricostano / @sauloperez for any additional info (or verification) you may need.
(I'm just a friend helping them out when I can)

Add COOP: "Coopdevs"

---

README.md

We're a small worker-owned web developer coop founded in 2018 🎉

Add Seattle Developers Cooperative

---

README.md

Sad, but true. Though some are transitioning into Bamboo Creative: https://bamboocreative.nz/

Added Root Systems handbook. Mentioned shutdown.

---

README.md

Hi, 
I was thinking to make some sort of repo like this, but I did some searching and found this one. Thanks for putting this together.
I'd like to add a few things I've come across in recent research and this is one book I really enjoyed.
It's basically a collection of essays paired with a bunch of profiles of real platform co-ops.

add book - Ours to Hack and to Own

---

README.md

Adding the coop I work with: https://blackshuck.co/

Add Black Shuck co-op

---

README.md

Blurb from their website:
> Position Development is a worker-run software development company with a
> focus on independent media, cultural institutions and socially minded
> organizations.

Add Position Development

---

README.md

- Add "Worker-owned, Founded 2013, Organizers of Austin Software Co-operatives Meetup

update Vulk Coop Notes

---

README.md

Adds Camplight cooperative to the cooperatives table.

Add Camplight cooperative

---

README.md

corrected url for
https://moodlight.team/
Thanks for this great info sources!
:)

corrected link readme

---

README.md

Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>

Add Cambá coop link

---

README.md

Add Autonomic

---

README.md

itopie is a Geneva-based Swiss tech cooperative (obvious from website if you speak French)

add Itopie

---

README.md

Add Zinc collective

---

README.md

Add informal.systems. 
Here's a post on our co-operative structure,  https://informal.systems/2020/09/21/informal-owners/

Add Informal.Systems

---

README.md

They mention being a worker cooperative on their [about page](https://designaction.org/about/).

Add Design Action Collective

---

README.md

Adds FullSteam Labs to North America section of coops directory

Add FullSteam Labs to directory

---

README.md

Hi there,
Can you add [Coop IT Easy](https://coopiteasy.be/) to the list? We're a worker owned coop providing ERP (development, hosting and support) for other coops (food coops mainly but not only).
All the best.

Add Coop IT Easy

---

README.md

A short movie explaining the free software world and cooperative movement

Add Cooperative Codes Video Link

---

README.md

Update README.md - Add Animorph

---

README.md

added slobodnadomena.hr to the list.

Added Slobodna domena coop

---

README.md

https://interstitial.coop/
Interstitial is a Cooperative and Public Benefit Corporation incorporated in Colorado with members distributed in the US and Canada, though we accept applicants from anywhere in the world.

Add Interstitial to North America section of the README.

---

README.md

Add Animus cooperative

---

README.md

See https://www.igalia.com/team/ for current number of workers

Update size for Igalia

---

README.md

Added our coop this time without the Mealtree website!

Added Gemify to North America

---

README.md

Hello, thank you for building this list.
We'd like to add Happyculture to this list wich is a french cooperative webagency (https://happyculture.coop/) created in 2013 and focused on social and solidarity economy. 
Feel free to correct me if any info is miscontributed. :)
Thank you!

Reference Happyculture

---

README.md

Hi,
Dalibo is a French cooperative since 2012, supporting PostgreSQL since 2005. You'll find the details at https://dalibo.com/en/philosophie.
Dalibo is 100% owned by it's workers.
Thanks @ramnes for the hint.

Link to Dalibo, France

---

README.md

Hi there,
First, thanks so much for maintaining this list. As I was changing jobs looking for more a democratic work environment, it's helped me see Tech cooperatives is a model more widely adopted than one might think.
This PR adds [Fairness](https://fairness.coop), a tech coop ("[SCOP](https://www.economie.gouv.fr/entreprises/definition-scop)" is the juridical status) based in Paris. We focus on building web platforms, agile project management consultancy, and do some other consultancy / auditing as well. Our focus is on eco-design and software quality.

Add Fairness

---

README.md

Add Empreinte Digitale

---

README.md

https://www.webalternatif.com
https://www.societe.com/societe/web-alternatif-517398939.html

Add Web|Alternatif

---

README.md

The company is under the French _SCOP_ legal status and is owned by employees.

Add Insite

---

README.md

Polycot Associates has been a worker-owned web dev agency since 2014. Founded in Austin,TX we are now distributed/virtual across the USA and Mexico. https://www.polycotassociates.com/

Add Polycot Associates worker-coop

---

README.md

Hi !
You can find all info on our website https://www.spotlab.net
Last statutes : https://www.spotlab.net/assets/pdf/Statuts-v2.3.pdf
Last kbis (french companies registration) : https://www.spotlab.net/assets/pdf/Kbis-2022-06.pdf

add spotlab

---

README.md

Hello there !
Adding Pathtech cooperative.
I didn't found any status document on their [website](https://pathtech.coop), but you can verify the COOP status on this site (french): https://www.societe.com/societe/pathtech-890152028.html

feat: add pathtech

---

README.md

See: [GOOD PRAXIS](https://goodpraxis.coop/)
[Entry in Co-ops UK](https://www.uk.coop/directory/good-praxis)

Add Good Praxis (Europe, UK, London)

---

README.md

Please include us in your listing, thank you!

Adding Rose Coded LLC to list of North American coops

---

README.md

Add roko.li coop

---

README.md

Our website : https://www.nethik.fr
You can find us on the official french coop list : https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000045979716
Thanks for this project :)

Added Nethik french cooperative (SCOP)

---

README.md

Thanks for compiling this list, helped us a lot when we founded our co-op [Village One](https://www.village.one)! ✌️

add Village One / https://www.village.one

---

README.md

Hello Henning it has been some time since we last met!  Would you please add TNG Worker Cooperative from Japan?   We became incorporated on November 10th!

Add TNG Worker Cooperative

---

README.md

https://libre-entreprise.org
See https://www.libre-entreprise.org/charte says : 
> prise de décision par consensus de l'ensemble des participants (salariés ?) ou, à défaut, en suivant le principe 1 personne = 1 voix ;
>     choix du représentant légal chaque année ;
>     si capital il y a, le capital détenu directement ou indirectement par les participants (salariés ?) composant l'entreprise doit être réparti entre eux de manière équilibrée.

Add Libre Entreprise network

---

README.md

Know of this coop near me, but I'm not a member.

Add weaver coop

---

README.md

Add the [TechGenossen](https://techgenossen.de/) to the list.
@tech-genossen

Add TechGenossen

---

README.md

https://troopers.coop (website only in french) 
The .coop domain should prove we are indeed a verified cooperative

Add Troopers

---

README.md

Thanks for taking care of this list!
Adding our coop gassagosso, you  can find "proof" of our cooperativeness here: https://annuaire-entreprises.data.gouv.fr/entreprise/gassagosso-843810037

Add gassagosso.coop

---

README.md

Add Syndicats eG

---

README.md

We're in the process of forming and looking for contributors.
Co-op rules (in progress): https://coop.ultri.com/
Open source platform:  https://platform.ultri.com/
Build in public app, under way: https://www.ultri.com/
Our first open source project:
https://handbook.opensociocracy.org/

Added Ultri

---

README.md

Add Ouvaton

---

DEFUNCT.md
README.md

The coop closed in 2022 and members launched Tetrabit coop

Removed Rabotnik (DK) and added to DEFUNCT.md

---

README.md

International Cooperative alliance worlwide techs co-op netowrk.

Add Patio ICA link

---

README.md

The existing link was broken. I believe this is the updated location.

Update README.md with Loomio Points link

---

README.md

Adding Librecoop and Simbiótica and align Spanish coops

Adding Librecoop and Simbiótica

---

README.md

Update Limeleaf Worker Collective URL
