README.md

The mentioned "e-book" was only available via an email signup so it's now irretrievable.

Remove huia.coop which is now defunct

---

README.md

The link I removed was to a LinkedIn page that says "Page not found"

Remove link to non-existent LinkedIn page

---

README.md

This domain http://eita.org.br/ has no content. This https://eita.coop.br/ seems the correct one.

EITA domain change

---

README.md

Gaia Host has shut down as of August 1, 2019 - extended to October 1 for hosting services and November 1 for domain transfers out.
see https://gaiahost.coop/help#status
in case the page goes down, archive.org link:
https://web.archive.org/web/20191217024930/https://gaiahost.coop/help
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hng/tech-coops/40)

Remove Gaia Host

---

README.md

In addition to the Camplight addition to the coop table, adds a link to our Medium blog posts.

Adds Camplight coop Medium articles link

---

README.md

In addition to the Camplight addition to the coop table, adds a link to our Medium blog posts.

Adds link to Camplight Assista product page

---

README.md

In addition to the Camplight addition to the coop table, adds a link to our Medium blog posts.

Adds Camplight coop Moodlight product link

---

README.md

I'm not sure if this fits better "Networks of coops" or "Products created by tech coops". They produce an open source postmates/doordash/grubhub clone exclusively for use by worker-owned couriers.
* https://coopcycle.org/en/
* https://www.youtube.com/watch?v=VrtnZHJ2Ha8

add CoopCycle

---

README.md

Although governed like a coop for a long time, since last year Kaleidos became [100% worker owned](https://blog.kaleidos.net/Kaleidos-pasa-a-ser-100-de-socios-empleados/).
\cc @diacritica

Add Kaleidos

---

README.md

Openflows has "Cooperative" in their full name, but not much on the website proving they're a cooperative (which they are).  They're listed in the NYC worker cooperative directory though:
https://nycworker.coop/co-op-directory/openflows/

Add Openflows

---

README.md

I haven't been in a tech coop for almost 5 years, but Quilted was defunct even then.  Radical Designs closed shop around that time as well.

Remove Quilted and Radical Designs

---

README.md

From the Feel Train website:
"So here we are, in not-so-early 2021, and I'm sad to say that Feel Train is no more, and in fact formally shut down at the tail end of 2019. "
Doesn't seem useful to keep around links to coops that don't exist anymore.

Removed now defunct Feel Train

---

DEFUNCT.md
README.md

For purposes of the main list being useful, it's nice not to show coops that don't exist. But
for information, we can keep a list of previous coops in a way that is more accessible than git history.
This PR is in response to some discussion on #100

Added DEFUNCT.md for keeping a record of past coops

---

README.md

Willow Bark Co-op (https://willowbark.org) is a new worker-owned freelancing group currently setting up our website and seeking more co-operators and clients. We are not currently registered, but we operate as a co-op sponsored by Platform 6 co-op until we can figure out registering ourselves: https://opencollective.com/willowbark

Add Willow Bark Co-op

---

README.md

Hi hng, hi tech-coops,
Heard about your repo, so here is my request to add our coop (and an open source product we develop) in the list.
Yaal is a 10 years old conventional company. Last year, we, a team of 5 people, **made a "fork" to create our own coop**: [Yaal Coop](https://yaal.coop/). In France, it is specifically a **SCIC**, a collective interest cooperative company, basically the same as a french **SCOP** but we can also chose to associate clients, suppliers, other cooperatives that we want to make them participate in our decision making.
Thank you!
And great project by the way.

Add Yaal coop company and Canaille project to tech-coops

---

DEFUNCT.md
README.md

We closed operations end of October.  Thanks!

Move Seattle Developers Coop to defunct list

---

README.md

Correct `http://cobudget.co/#/` to `https://cobudget.com`.

Fix Cobudget link typo.

---

README.md

From https://drivers.coop/about:
> We are a driver-owned ridehailing cooperative in New York City. Drivers make more on each trip, all profits go back to drivers, and drivers have democratic control over the decisions that affect their lives.
>
> Our mission is to end exploitative conditions in the for-hire vehicle industry through system change– putting drivers in the driver’s seat of the platform economy.

Add The Drivers Cooperative

---

README.md

FikaWorks is a coop/collective incorporated in Netherlands, but with members from multiple European countries. You can read more about us here: https://fika.works/blog/what-fikaworks-offers-clients/

Add FikaWorks

---

README.md

Baseline is a AI consulting worker-owned coop based in Quebec City. See section "About Us" of the website. Here is the link to the website: https://baseline.quebec/en/

Add Baseline to North America

---

README.md

This is a PR to add Probesys cooperative society https://www.probesys.com/
We exist as a SCOP (french for Worker Cooperative Society  of Production) since 2003, we have also created a cooperative group with another society that we have transformed into a SCOP in 2017.
We are referenced in the French SCOP movement: https://www.les-scop.coop/probesys

Add Probesys

---

README.md

Didn't notice that the `|` character in `Web|Alternatif` (#152) broke the markdown table :see_no_evil:

Escape pipe char in markdown table

---

README.md

We don't really put much about our co-op status on our website, but you can see our resolution of cooperative status in the companies register here: https://app.companiesoffice.govt.nz/companies/app/ui/pages/companies/6615493/documents

Add Ion Technologies to list of co-ops in Oceania

---

README.md

https://www.indiciopponibili.com/
From the website is not immediately understandable that it's a Coop, but there are many italian websites easily found through google where it's explicit eg. https://www.legacoop.bologna.it/cooperative/indici-opponibili-societa-cooperativa/

Added Indici Opponibili

---

DEFUNCT.md
README.md

The domain is for sale. The coop site appears to have been down for a [number of years](https://web.archive.org/web/20240000000000*/http://brierwood.coop/)

Archive Brierwood Coop
